#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXAMPLE_FILE="${ROOT_DIR}/.env.example"
ENV_FILE="${ROOT_DIR}/.env.local"

default_server="server.slsknet.org:2416"
if [ -f "${EXAMPLE_FILE}" ]; then
  example_server="$(awk -F= '/^NSS_TEST_SERVER=/{print $2}' "${EXAMPLE_FILE}" | tail -n1)"
  if [ -n "${example_server:-}" ]; then
    default_server="${example_server}"
  fi
fi

if [ -f "${ENV_FILE}" ]; then
  read -r -p ".env.local already exists. Overwrite it? [y/N]: " overwrite
  overwrite="${overwrite:-N}"
  case "${overwrite}" in
    y|Y|yes|YES) ;;
    *)
      echo "Aborted. Existing .env.local was kept."
      exit 0
      ;;
  esac
fi

read -r -p "Soulseek server [${default_server}]: " server
server="${server:-${default_server}}"

while :; do
  read -r -p "Username: " username
  if [ -n "${username}" ]; then
    break
  fi
  echo "Username cannot be empty."
done

while :; do
  read -r -s -p "Password: " password
  echo
  if [ -n "${password}" ]; then
    break
  fi
  echo "Password cannot be empty."
done

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/setup_credentials_wizard.sh
NSS_TEST_SERVER=${server}
NSS_TEST_USERNAME=${username}
NSS_TEST_PASSWORD=${password}
EOF

chmod 600 "${ENV_FILE}" || true

echo
echo "Created ${ENV_FILE}"
echo "Load it in your shell with:"
echo "  set -a; source .env.local; set +a"
